### ISSUE TITLE
[FEAT] 합성 데이터를 학습해보자!

### ISSUE THREAD

**Issue by suhyun6363** [boostcampaitech7/level2-cv-datacentric-cv-21#43]
## Background
- 아래 그림처럼 3세트 30장 언어당 총 90장에 합성 데이터를 드디어 생성 완료했습니다! 만든 합성 데이터를 아래 3번의 실험을 진행해보려고 합니다.
![document_1_0](https://github.com/user-attachments/assets/a9ed676c-dcd3-46a3-8d1c-6a376bbe88d6)
![document_1_1](https://github.com/user-attachments/assets/a5f9f735-bbae-4189-834f-7b53724eb5f1)
![document_1_2](https://github.com/user-attachments/assets/280d88e4-675b-42db-b27a-00ebdc4d0394)

## Todo
- [x] 합성 데이터셋 fine-tuning > 학습된 모델을 ckpt를 불러와 기존 데이터셋 fine-tuning
- [ ] 기존 데이터셋을 학습한 최고성능 모델 ckpt를 불러와 합성 데이터셋 fine-tuning
- [ ] 기존+합성 학습
