### ISSUE TITLE
[FEAT] Markdown 추가하기

### ISSUE THREAD

**Issue by namgyu-youn** [boostcampaitech7/level2-cv-datacentric-cv-21#5]
## Background
- 현재 pipeline의 "dataset.py", "train.py"에는 주석이 추가되어 있어 상대적으로 이해하기 쉽지만, 다른 파일들은 아직 주석이 없습니다.
- 코드 리뷰를 해보면서, 적당한 markdown을 집어넣어 가독성을 높이는 것이 목표입니다.
- 최종 목표는 현재 pipeline에 대한 코드 리뷰를 마치고, 다른 팀원들이 이해하기 쉽도록 문서화하는 것입니다.

## Todo
- [ ] Update markdown : east_dataset.py
- [ ] Update markdown : detect.py
- [ ] Code_Review 마무리하기

## See also
- #
